//! The RPC API. Every method is declared exactly once in the `api!` invocation
//! below, which generates:
//! - `Request`: the typed request enum (wire form `{"method", "params"}`),
//! - `METHODS`: every method name (used by the CLI parity test),
//! - `ts_method_map()`: a TypeScript `Methods` interface mapping each method
//!   to its params and result types,
//! - `export_ts()`: exports all param/result types with ts-rs.

use crate::types::*;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

macro_rules! api {
    ($( $(#[doc = $doc:literal])* $variant:ident = $name:literal ($params:ty) -> $result:ty; )*) => {
        /// A typed RPC request. Serialized as `{"method": ..., "params": ...}`.
        #[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
        #[serde(tag = "method", content = "params")]
        pub enum Request {
            $( $(#[doc = $doc])* #[serde(rename = $name)] $variant($params), )*
        }

        impl Request {
            pub fn method(&self) -> &'static str {
                match self { $( Request::$variant(_) => $name, )* }
            }
        }

        /// Every RPC method name, in declaration order.
        pub const METHODS: &[&str] = &[ $( $name ),* ];

        /// (method, doc) pairs for help output.
        pub const METHOD_DOCS: &[(&str, &str)] = &[ $( ($name, concat!($($doc),*)) ),* ];

        /// TypeScript source for the `Methods` interface.
        pub fn ts_method_map() -> String {
            let cfg = ts_rs::Config::default();
            let mut imports = std::collections::BTreeSet::new();
            let mut body = String::new();
            $(
                let p = <$params as TS>::name(&cfg);
                let r = <$result as TS>::name(&cfg);
                imports.insert(p.clone());
                imports.insert(r.clone());
                body.push_str(&format!("  \"{}\": {{ params: {}; result: {} }};\n", $name, p, r));
            )*
            let mut out = String::from("// Generated by gen-bindings from crates/protocol/src/api.rs. Do not edit.\n");
            for i in &imports {
                out.push_str(&format!("import type {{ {i} }} from \"./{i}\";\n"));
            }
            out.push_str("\nexport interface Methods {\n");
            out.push_str(&body);
            out.push_str("}\n\nexport type MethodName = keyof Methods;\n\nexport const METHODS: MethodName[] = [\n");
            $( out.push_str(&format!("  \"{}\",\n", $name)); )*
            out.push_str("];\n");
            out
        }

        /// Export every param and result type (and their dependencies).
        pub fn export_ts(dir: &std::path::Path) -> Result<(), ts_rs::ExportError> {
            let cfg = ts_rs::Config::default().with_out_dir(dir);
            $(
                <$params as TS>::export_all(&cfg)?;
                <$result as TS>::export_all(&cfg)?;
            )*
            Ok(())
        }
    };
}

/// Params or result with no fields.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct Empty {}

// ---- session -------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct HelloParams {
    /// Display name for this client; used as event origin.
    pub client_name: String,
    pub protocol_version: u32,
    /// Required when the daemon was started with `--token`.
    #[serde(default)]
    pub token: Option<String>,
    /// The person using this client: owns this connection's undo history
    /// (default: the daemon host's user, so local clients share one). A
    /// seat with this name (any case) is joined automatically if it is the
    /// only match; in a project without seats, one is created for them.
    #[serde(default)]
    pub user: Option<String>,
    /// Join this existing seat instead of matching by `user`.
    #[serde(default)]
    pub seat: Option<String>,
    /// Match a seat by `user` (default true). False stays unseated.
    #[serde(default)]
    pub auto_seat: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct HelloResult {
    pub protocol_version: u32,
    pub server_version: String,
    pub client_id: String,
    pub role: Role,
    /// The seat this client joined, if any.
    pub seat: Option<String>,
    /// No seat matched unambiguously: ask the user to join a seat
    /// (`seat.claim`), create one (`seat.create`), or ignore
    /// (`seat.create` with `saved: false`).
    pub choose_seat: bool,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SubscribeParams {
    /// Event types to receive (e.g. `["param_changed"]`). All if omitted.
    #[serde(default)]
    pub types: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SubscribeResult {
    /// Sequence number at subscription time.
    #[ts(type = "number")]
    pub seq: u64,
}

// ---- params --------------------------------------------------------------

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ParamListParams {
    #[serde(default)]
    pub prefix: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ParamListResult {
    pub params: Vec<ParamInfo>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ParamGetParams {
    pub path: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ParamSetParams {
    pub path: String,
    /// Clamped to the parameter's range.
    pub value: f64,
}

// ---- instruments, channels, routing ----------------------------------------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct InstrumentTypeInfo {
    #[serde(rename = "type")]
    #[ts(rename = "type")]
    pub kind: InstrumentType,
    pub label: String,
    pub default_id: String,
    /// Outputs of an instance with the default id.
    pub outputs: Vec<OutputInfo>,
    /// Parameters of an instance with the default id.
    pub params: Vec<ParamInfo>,
    /// Knob pages of an instance with the default id.
    pub knob_pages: Vec<KnobPage>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct InstrumentTypesResult {
    pub types: Vec<InstrumentTypeInfo>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct InstrumentListResult {
    pub instruments: Vec<InstrumentInfo>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct InstrumentAddParams {
    #[serde(rename = "type")]
    #[ts(rename = "type")]
    pub kind: InstrumentType,
    /// Defaults to the type's default id (`drums`, `bass`), numbered if taken.
    #[serde(default)]
    pub id: Option<String>,
    #[serde(default)]
    pub name: Option<String>,
    /// Route the main output to this existing channel. By default it goes to
    /// the first empty channel in display order, or a new one if none is empty.
    #[serde(default)]
    pub channel: Option<u32>,
    /// Leave the main output unrouted (no new channel).
    #[serde(default)]
    pub no_channel: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct InstrumentRemoveParams {
    pub id: String,
    /// Keep the channels its outputs fed even if they are left empty.
    #[serde(default)]
    pub keep_channels: bool,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ChannelAddParams {
    #[serde(default)]
    pub name: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ChannelRemoveParams {
    pub n: u32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ChannelRenameParams {
    pub n: u32,
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ChannelMoveParams {
    pub n: u32,
    /// New display position, 1 = leftmost.
    pub position: u32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct RouteSetParams {
    /// `drums` (main out) or `drums.kick` (direct out).
    pub source: String,
    /// Channel number, or omitted/null to unroute (a direct out then plays
    /// through its instrument's main mix again).
    #[serde(default)]
    pub channel: Option<u32>,
    /// If the channel already has other sources, move them to this source's
    /// current channel (if it had none, they stay and share the channel).
    #[serde(default)]
    pub swap: bool,
}

// ---- history and journal -------------------------------------------------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct HistoryStepResult {
    /// What was undone or redone; null if the stack was empty.
    pub label: Option<String>,
    /// Keys it changed.
    pub changed: Vec<String>,
    /// Keys left alone because another user changed them since.
    pub skipped: Vec<String>,
    pub history: HistoryInfo,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct JournalGetParams {
    /// Only entries with a greater seq.
    #[serde(default)]
    #[ts(type = "number | null")]
    pub since: Option<u64>,
    /// At most this many (newest), default 100.
    #[serde(default)]
    pub limit: Option<u32>,
    /// Only this user's entries.
    #[serde(default)]
    pub user: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct JournalGetResult {
    /// Oldest first.
    pub entries: Vec<JournalEntry>,
}

// ---- pattern -------------------------------------------------------------

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct PatternGetParams {
    /// Drum instrument id; defaults to the first `tr808`.
    #[serde(default)]
    pub instrument: Option<String>,
    #[serde(default)]
    pub voice: Option<Voice>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct PatternResult {
    pub instrument: String,
    /// Active length (`sequencer.length`).
    pub length: u32,
    pub tracks: Vec<TrackPattern>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct NotesGetParams {
    /// Note instrument id; defaults to the first `tb303`.
    #[serde(default)]
    pub instrument: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct NotesSetParams {
    /// Note instrument id; defaults to the first `tb303`.
    #[serde(default)]
    pub instrument: Option<String>,
    /// Steps from step 0; missing trailing steps become rests.
    pub steps: Vec<NoteStep>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct NoteSetParams {
    /// Note instrument id; defaults to the first `tb303`.
    #[serde(default)]
    pub instrument: Option<String>,
    /// 0-based step index.
    pub step: u32,
    pub note: NoteStep,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct NotesResult {
    pub instrument: String,
    /// Active length (`sequencer.length`).
    pub length: u32,
    /// All `MAX_STEPS` steps.
    pub steps: Vec<NoteStep>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct PatternSetParams {
    /// Drum instrument id; defaults to the first `tr808`.
    #[serde(default)]
    pub instrument: Option<String>,
    pub voice: Voice,
    /// Step levels from step 0; missing trailing steps are cleared.
    pub steps: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SetStepParams {
    /// Drum instrument id; defaults to the first `tr808`.
    #[serde(default)]
    pub instrument: Option<String>,
    pub voice: Voice,
    /// 0-based step index.
    pub step: u32,
    /// 0 = off, 1 = on, 2 = accent.
    pub level: u8,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ToggleStepParams {
    /// Drum instrument id; defaults to the first `tr808`.
    #[serde(default)]
    pub instrument: Option<String>,
    pub voice: Voice,
    pub step: u32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct StepResult {
    pub instrument: String,
    pub voice: Voice,
    pub step: u32,
    pub level: u8,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct PatternClearParams {
    /// Drum instrument id; defaults to the first `tr808`.
    #[serde(default)]
    pub instrument: Option<String>,
    /// Clear only this voice; all voices if omitted.
    #[serde(default)]
    pub voice: Option<Voice>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct TriggerParams {
    /// Defaults to the seat's focus (for `voice`, the first `tr808` unless
    /// the focus is one).
    #[serde(default)]
    pub instrument: Option<String>,
    /// Drum voice to play (drum instruments).
    #[serde(default)]
    pub voice: Option<Voice>,
    /// MIDI note to play for half a step (a drum machine plays the voice
    /// on that GM note).
    #[serde(default)]
    pub note: Option<u8>,
    /// 0..1, defaults to 1.
    #[serde(default)]
    pub velocity: Option<f32>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct NoteParams {
    /// Instrument id; defaults to the caller's seat focus (or the host
    /// seat's, for a client without a seat).
    #[serde(default)]
    pub instrument: Option<String>,
    /// MIDI note (0..127; a drum machine plays the voice on that GM note).
    pub note: u8,
    /// 0..1, defaults to 1 (0.95 and up plays accented). Ignored by note-off.
    #[serde(default)]
    pub velocity: Option<f32>,
}

// ---- controller ----------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct PadParams {
    /// 0-based row (track).
    pub row: u32,
    /// 0-based column within the current page.
    pub col: u32,
    /// true = press, false = release. Omit for a full tap.
    #[serde(default)]
    pub pressed: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct KnobParams {
    /// 0-based knob index.
    pub index: u32,
    /// Normalized position 0..1 (as from a 0..127 MIDI CC).
    pub value: f64,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ControllerModeParams {
    /// Which 8-step page the grid shows (0-based).
    #[serde(default)]
    pub page: Option<u32>,
    #[serde(default)]
    pub follow: Option<bool>,
}

// ---- midi ----------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct MidiPortsResult {
    pub inputs: Vec<String>,
    pub outputs: Vec<String>,
    pub connections: Vec<MidiConnection>,
    /// This machine's hardware entries (`midi-devices.json`).
    pub devices: Vec<MidiDevice>,
    /// Seat the engine host's devices use.
    pub seat: String,
    /// Seat pinned with `midi.set_seat`, if any.
    pub pinned_seat: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct MidiConnectParams {
    /// Input port name (exact or case-insensitive substring).
    pub input: String,
    /// Output port for feedback (LEDs). Defaults to the output matching the
    /// input for a Livid Block.
    #[serde(default)]
    pub output: Option<String>,
    /// Logical device name. Default: the saved one, else made from the port
    /// name.
    #[serde(default)]
    pub name: Option<String>,
    /// Default: the saved one, else `livid_block` for ports named like a
    /// Block, else `generic`.
    #[serde(default)]
    pub profile: Option<DeviceProfile>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct MidiDisconnectParams {
    pub input: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct MidiRenameParams {
    /// Port name or current logical name (exact or case-insensitive
    /// substring of a port).
    pub device: String,
    /// New logical name.
    pub name: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct MidiSetSeatParams {
    /// Seat for this machine's devices; omit to unpin (they then follow
    /// the local user).
    #[serde(default)]
    pub seat: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct MidiInputParams {
    /// Logical device name the input comes from.
    pub device: String,
    /// Raw MIDI bytes of one message, e.g. `[144, 60, 100]`.
    pub data: Vec<u8>,
    /// Seat to apply; default: the caller's, else the host seat. A Livid
    /// Block only edits the host seat (its LEDs show that one).
    #[serde(default)]
    pub seat: Option<String>,
}

// ---- seats ---------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SeatListResult {
    pub seats: Vec<Seat>,
    /// The caller's seat.
    pub you: Option<String>,
    /// Seat the engine host's devices use.
    pub host: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SeatNameParams {
    pub name: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SeatCreateParams {
    /// Default: the caller's user name (numbered if taken).
    #[serde(default)]
    pub name: Option<String>,
    /// Save with the project (default true). False = "ignore": a seat for
    /// this session only.
    #[serde(default)]
    pub saved: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SeatFocusParams {
    /// Default: the caller's seat.
    #[serde(default)]
    pub seat: Option<String>,
    pub instrument: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SeatPageParams {
    #[serde(default)]
    pub seat: Option<String>,
    /// Knob page id of the focused instrument, e.g. `decay`.
    pub page: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SeatBindParams {
    #[serde(default)]
    pub seat: Option<String>,
    pub binding: NoteBinding,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SeatUnbindParams {
    #[serde(default)]
    pub seat: Option<String>,
    /// 0-based index into the seat's bindings.
    pub index: u32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SeatMapCcParams {
    #[serde(default)]
    pub seat: Option<String>,
    pub map: CcMap,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SeatUnmapCcParams {
    #[serde(default)]
    pub seat: Option<String>,
    pub device: String,
    pub cc: u8,
    /// Only the map on this channel; maps on any channel if omitted.
    #[serde(default)]
    pub channel: Option<u8>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SeatLearnCcParams {
    #[serde(default)]
    pub seat: Option<String>,
    /// Parameter the next CC moved maps to; omit to cancel learning.
    #[serde(default)]
    pub param: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SeatFollowKnobsParams {
    #[serde(default)]
    pub seat: Option<String>,
    /// Replaces the device's entry; empty `ccs` removes it.
    pub follow: KnobFollow,
}

// ---- project -------------------------------------------------------------

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ProjectSaveParams {
    /// Engine-side bundle path (e.g. `songs/beat.4s`). Relative paths resolve
    /// under the daemon's data dir. Defaults to the current project path.
    #[serde(default)]
    pub path: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ProjectLoadParams {
    pub path: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ProjectListResult {
    /// Project bundles found in the daemon's projects dir (engine-side paths).
    pub projects: Vec<String>,
}

// ---- render --------------------------------------------------------------

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct RenderParams {
    /// Number of 4/4 bars to render (default 1).
    #[serde(default)]
    pub bars: Option<f64>,
    /// Extra seconds after the last bar so tails ring out (default 0).
    #[serde(default)]
    pub tail: Option<f64>,
    /// Engine-side WAV path. Relative paths resolve under the data dir.
    #[serde(default)]
    pub path: Option<String>,
    #[serde(default)]
    pub sample_rate: Option<u32>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct RenderResult {
    pub path: String,
    pub sample_rate: u32,
    pub duration: f64,
    /// Peak absolute sample value across channels.
    pub peak: f32,
    pub rms: f32,
    pub left: Level,
    pub right: Level,
    /// Onset times (seconds) detected from the audio itself.
    pub onsets: Vec<f64>,
    /// What the sequencer actually fired, for comparison with `onsets`.
    pub triggers: Vec<RenderTrigger>,
}

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct Level {
    pub peak: f32,
    pub rms: f32,
}

// ---------------------------------------------------------------------------

api! {
    /// Identify this client and check protocol compatibility.
    Hello = "session.hello" (HelloParams) -> HelloResult;
    /// Full state snapshot.
    StateGet = "state.get" (Empty) -> Snapshot;
    /// Start receiving `event` notifications on this connection.
    EventsSubscribe = "events.subscribe" (SubscribeParams) -> SubscribeResult;
    /// Stop receiving events.
    EventsUnsubscribe = "events.unsubscribe" (Empty) -> Empty;

    /// List parameters, optionally filtered by path prefix.
    ParamList = "param.list" (ParamListParams) -> ParamListResult;
    /// Read one parameter.
    ParamGet = "param.get" (ParamGetParams) -> ParamValue;
    /// Set one parameter (clamped to its range).
    ParamSet = "param.set" (ParamSetParams) -> ParamValue;

    /// Start the sequencer from step 1.
    TransportPlay = "transport.play" (Empty) -> TransportState;
    /// Stop the sequencer.
    TransportStop = "transport.stop" (Empty) -> TransportState;

    /// Available instrument types, with their outputs and parameters.
    InstrumentTypes = "instrument.types" (Empty) -> InstrumentTypesResult;
    /// Instruments in creation order.
    InstrumentList = "instrument.list" (Empty) -> InstrumentListResult;
    /// Add an instrument; by default on the first empty channel, else a new one.
    InstrumentAdd = "instrument.add" (InstrumentAddParams) -> InstrumentInfo;
    /// Remove an instrument (and channels left empty, unless kept).
    InstrumentRemove = "instrument.remove" (InstrumentRemoveParams) -> Graph;
    /// Add a mixer channel (lowest free number).
    ChannelAdd = "channel.add" (ChannelAddParams) -> ChannelInfo;
    /// Remove a mixer channel; sources routed to it are unrouted.
    ChannelRemove = "channel.remove" (ChannelRemoveParams) -> Graph;
    /// Rename a mixer channel.
    ChannelRename = "channel.rename" (ChannelRenameParams) -> ChannelInfo;
    /// Move a mixer channel to a new display position.
    ChannelMove = "channel.move" (ChannelMoveParams) -> Graph;
    /// Route an instrument output to a channel, or unroute it.
    RouteSet = "route.set" (RouteSetParams) -> Graph;

    /// Undo the caller's last change, leaving keys another user changed since.
    HistoryUndo = "history.undo" (Empty) -> HistoryStepResult;
    /// Redo the caller's last undo.
    HistoryRedo = "history.redo" (Empty) -> HistoryStepResult;
    /// The caller's undo and redo stacks.
    HistoryGet = "history.get" (Empty) -> HistoryInfo;
    /// Recent journal entries: every request that could change state.
    JournalGet = "journal.get" (JournalGetParams) -> JournalGetResult;

    /// Read a drum pattern (one voice or all).
    PatternGet = "pattern.get" (PatternGetParams) -> PatternResult;
    /// Replace one voice's steps.
    PatternSet = "pattern.set" (PatternSetParams) -> TrackPattern;
    /// Set one step's level.
    PatternSetStep = "pattern.set_step" (SetStepParams) -> StepResult;
    /// Toggle one step between off and on.
    PatternToggleStep = "pattern.toggle_step" (ToggleStepParams) -> StepResult;
    /// Clear one voice or the whole pattern.
    PatternClear = "pattern.clear" (PatternClearParams) -> PatternResult;
    /// Read a note pattern.
    PatternGetNotes = "pattern.get_notes" (NotesGetParams) -> NotesResult;
    /// Replace a note pattern.
    PatternSetNotes = "pattern.set_notes" (NotesSetParams) -> NotesResult;
    /// Set one step of a note pattern.
    PatternSetNote = "pattern.set_note" (NoteSetParams) -> NotesResult;

    /// Play a drum voice or a note immediately (audition).
    VoiceTrigger = "voice.trigger" (TriggerParams) -> Empty;

    /// Start a held note (like a key down on a keyboard). The caller holds
    /// it until `voice.note_off` for the same note.
    VoiceNoteOn = "voice.note_on" (NoteParams) -> Empty;
    /// Release a note this caller is holding (like a key up).
    VoiceNoteOff = "voice.note_off" (NoteParams) -> Empty;

    /// Controller state (focus, knob page, grid page, LEDs, device).
    ControllerGet = "controller.get" (Empty) -> ControllerState;
    /// Press/release a grid pad, as if on the Livid Block.
    ControllerPress = "controller.press" (PadParams) -> ControllerState;
    /// Set a knob's parameter to a position, as if on the Livid Block (no
    /// pickup).
    ControllerKnob = "controller.knob" (KnobParams) -> ControllerState;
    /// Change the grid page or follow.
    ControllerSetMode = "controller.set_mode" (ControllerModeParams) -> ControllerState;

    /// List MIDI ports, connections, and this machine's device names.
    MidiPorts = "midi.ports" (Empty) -> MidiPortsResult;
    /// Connect a MIDI input (and optional output) as a named device.
    MidiConnect = "midi.connect" (MidiConnectParams) -> MidiPortsResult;
    /// Disconnect a MIDI input.
    MidiDisconnect = "midi.disconnect" (MidiDisconnectParams) -> MidiPortsResult;
    /// Rename a device (the logical name seats bind to).
    MidiRename = "midi.rename" (MidiRenameParams) -> MidiPortsResult;
    /// Pin the seat this machine's devices use, or unpin it.
    MidiSetSeat = "midi.set_seat" (MidiSetSeatParams) -> MidiPortsResult;
    /// Feed one raw MIDI message from a logical device (as a bridge does).
    MidiInput = "midi.input" (MidiInputParams) -> Empty;

    /// Seats, who sits where, and the host seat.
    SeatList = "seat.list" (Empty) -> SeatListResult;
    /// Join an existing seat.
    SeatClaim = "seat.claim" (SeatNameParams) -> SeatListResult;
    /// Create a seat and join it.
    SeatCreate = "seat.create" (SeatCreateParams) -> SeatListResult;
    /// Leave your seat.
    SeatLeave = "seat.leave" (Empty) -> SeatListResult;
    /// Delete a seat; its occupants become unseated. In a project with no
    /// other saved seats, the host user's seat is recreated at once.
    SeatRemove = "seat.remove" (SeatNameParams) -> SeatListResult;
    /// Focus an instrument: `focus` bindings, the Block, and following
    /// knobs play it.
    SeatFocus = "seat.focus" (SeatFocusParams) -> Seat;
    /// Choose the knob page of the focused instrument.
    SeatPage = "seat.page" (SeatPageParams) -> Seat;
    /// Add a note binding.
    SeatBind = "seat.bind" (SeatBindParams) -> Seat;
    /// Remove a note binding.
    SeatUnbind = "seat.unbind" (SeatUnbindParams) -> Seat;
    /// Map a CC to a parameter.
    SeatMapCc = "seat.map_cc" (SeatMapCcParams) -> Seat;
    /// Remove CC maps.
    SeatUnmapCc = "seat.unmap_cc" (SeatUnmapCcParams) -> Seat;
    /// Map the next CC moved on this seat's devices to a parameter.
    SeatLearnCc = "seat.learn_cc" (SeatLearnCcParams) -> Seat;
    /// Make a device's CCs control the focused instrument's knob page.
    SeatFollowKnobs = "seat.follow_knobs" (SeatFollowKnobsParams) -> Seat;

    /// Reset to a fresh default project.
    ProjectNew = "project.new" (Empty) -> ProjectInfo;
    /// Save the project bundle.
    ProjectSave = "project.save" (ProjectSaveParams) -> ProjectInfo;
    /// Load a project bundle.
    ProjectLoad = "project.load" (ProjectLoadParams) -> ProjectInfo;
    /// List project bundles in the daemon's projects dir.
    ProjectList = "project.list" (Empty) -> ProjectListResult;

    /// Render the current project offline to a WAV and analyze it.
    RenderOffline = "render.offline" (RenderParams) -> RenderResult;
    /// Audio device status.
    EngineStatus = "engine.status" (Empty) -> AudioStatus;

    /// Daemon identity: pid, version, URL, data dir, uptime.
    DaemonInfo = "daemon.info" (Empty) -> DaemonInfo;
    /// Shut the daemon down gracefully (responds first, then exits).
    DaemonShutdown = "daemon.shutdown" (Empty) -> Empty;
}

/// Build a `Request` from a method name and JSON params (missing/null params
/// are treated as `{}`).
pub fn parse_request(method: &str, params: Option<serde_json::Value>) -> Result<Request, String> {
    let params = match params {
        None | Some(serde_json::Value::Null) => serde_json::json!({}),
        Some(p) => p,
    };
    if !METHODS.contains(&method) {
        return Err(format!("unknown method '{method}'"));
    }
    serde_json::from_value(serde_json::json!({ "method": method, "params": params }))
        .map_err(|e| format!("invalid params for '{method}': {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn request_wire_format() {
        let r = Request::ParamSet(ParamSetParams { path: "mixer.1.volume".into(), value: 0.35 });
        let j = serde_json::to_value(&r).unwrap();
        assert_eq!(j["method"], "param.set");
        assert_eq!(j["params"]["value"], 0.35);
        assert_eq!(r.method(), "param.set");
    }

    #[test]
    fn parse_with_missing_params() {
        assert!(matches!(parse_request("state.get", None).unwrap(), Request::StateGet(_)));
        assert!(matches!(
            parse_request("pattern.clear", Some(serde_json::Value::Null)).unwrap(),
            Request::PatternClear(PatternClearParams { instrument: None, voice: None })
        ));
        assert!(parse_request("nope", None).is_err());
        assert!(parse_request("param.set", Some(serde_json::json!({"path": 1}))).is_err());
    }
}
