//! The RPC API. Every method is declared exactly once in the `api!` invocation
//! below, which generates:
//! - `Request`: the typed request enum (wire form `{"method", "params"}`),
//! - `METHODS`: every method name (used by the CLI parity test),
//! - `ts_method_map()`: a TypeScript `Methods` interface mapping each method
//!   to its params and result types,
//! - `export_ts()`: exports all param/result types with ts-rs.

use crate::types::*;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

macro_rules! api {
    ($( $(#[doc = $doc:literal])* $variant:ident = $name:literal ($params:ty) -> $result:ty; )*) => {
        /// A typed RPC request. Serialized as `{"method": ..., "params": ...}`.
        #[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
        #[serde(tag = "method", content = "params")]
        pub enum Request {
            $( $(#[doc = $doc])* #[serde(rename = $name)] $variant($params), )*
        }

        impl Request {
            pub fn method(&self) -> &'static str {
                match self { $( Request::$variant(_) => $name, )* }
            }
        }

        /// Every RPC method name, in declaration order.
        pub const METHODS: &[&str] = &[ $( $name ),* ];

        /// (method, doc) pairs for help output.
        pub const METHOD_DOCS: &[(&str, &str)] = &[ $( ($name, concat!($($doc),*)) ),* ];

        /// TypeScript source for the `Methods` interface.
        pub fn ts_method_map() -> String {
            let cfg = ts_rs::Config::default();
            let mut imports = std::collections::BTreeSet::new();
            let mut body = String::new();
            $(
                let p = <$params as TS>::name(&cfg);
                let r = <$result as TS>::name(&cfg);
                imports.insert(p.clone());
                imports.insert(r.clone());
                body.push_str(&format!("  \"{}\": {{ params: {}; result: {} }};\n", $name, p, r));
            )*
            let mut out = String::from("// Generated by gen-bindings from crates/protocol/src/api.rs. Do not edit.\n");
            for i in &imports {
                out.push_str(&format!("import type {{ {i} }} from \"./{i}\";\n"));
            }
            out.push_str("\nexport interface Methods {\n");
            out.push_str(&body);
            out.push_str("}\n\nexport type MethodName = keyof Methods;\n\nexport const METHODS: MethodName[] = [\n");
            $( out.push_str(&format!("  \"{}\",\n", $name)); )*
            out.push_str("];\n");
            out
        }

        /// Export every param and result type (and their dependencies).
        pub fn export_ts(dir: &std::path::Path) -> Result<(), ts_rs::ExportError> {
            let cfg = ts_rs::Config::default().with_out_dir(dir);
            $(
                <$params as TS>::export_all(&cfg)?;
                <$result as TS>::export_all(&cfg)?;
            )*
            Ok(())
        }
    };
}

/// Params or result with no fields.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct Empty {}

// ---- session -------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct HelloParams {
    /// Display name for this client; used as event origin.
    pub client_name: String,
    pub protocol_version: u32,
    /// Required when the daemon was started with `--token`.
    #[serde(default)]
    pub token: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct HelloResult {
    pub protocol_version: u32,
    pub server_version: String,
    pub client_id: String,
    pub role: Role,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SubscribeParams {
    /// Event types to receive (e.g. `["param_changed"]`). All if omitted.
    #[serde(default)]
    pub types: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SubscribeResult {
    /// Sequence number at subscription time.
    #[ts(type = "number")]
    pub seq: u64,
}

// ---- params --------------------------------------------------------------

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ParamListParams {
    #[serde(default)]
    pub prefix: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ParamListResult {
    pub params: Vec<ParamInfo>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ParamGetParams {
    pub path: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ParamSetParams {
    pub path: String,
    /// Clamped to the parameter's range.
    pub value: f64,
}

// ---- instruments, channels, routing ----------------------------------------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct InstrumentTypeInfo {
    #[serde(rename = "type")]
    #[ts(rename = "type")]
    pub kind: InstrumentType,
    pub label: String,
    pub default_id: String,
    /// Outputs of an instance with the default id.
    pub outputs: Vec<OutputInfo>,
    /// Parameters of an instance with the default id.
    pub params: Vec<ParamInfo>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct InstrumentTypesResult {
    pub types: Vec<InstrumentTypeInfo>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct InstrumentListResult {
    pub instruments: Vec<InstrumentInfo>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct InstrumentAddParams {
    #[serde(rename = "type")]
    #[ts(rename = "type")]
    pub kind: InstrumentType,
    /// Defaults to the type's default id (`drums`, `bass`), numbered if taken.
    #[serde(default)]
    pub id: Option<String>,
    #[serde(default)]
    pub name: Option<String>,
    /// Route the main output to this existing channel instead of a new one.
    #[serde(default)]
    pub channel: Option<u32>,
    /// Leave the main output unrouted (no new channel).
    #[serde(default)]
    pub no_channel: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct InstrumentRemoveParams {
    pub id: String,
    /// Keep the channels its outputs fed even if they are left empty.
    #[serde(default)]
    pub keep_channels: bool,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ChannelAddParams {
    #[serde(default)]
    pub name: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ChannelRemoveParams {
    pub n: u32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ChannelRenameParams {
    pub n: u32,
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct RouteSetParams {
    /// `drums` (main out) or `drums.kick` (direct out).
    pub source: String,
    /// Channel number, or omitted/null to unroute (a direct out then plays
    /// through its instrument's main mix again).
    #[serde(default)]
    pub channel: Option<u32>,
}

// ---- pattern -------------------------------------------------------------

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct PatternGetParams {
    /// Drum instrument id; defaults to the first `tr808`.
    #[serde(default)]
    pub instrument: Option<String>,
    #[serde(default)]
    pub voice: Option<Voice>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct PatternResult {
    pub instrument: String,
    /// Active length (`sequencer.length`).
    pub length: u32,
    pub tracks: Vec<TrackPattern>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct NotesGetParams {
    /// Note instrument id; defaults to the first `tb303`.
    #[serde(default)]
    pub instrument: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct NotesSetParams {
    /// Note instrument id; defaults to the first `tb303`.
    #[serde(default)]
    pub instrument: Option<String>,
    /// Steps from step 0; missing trailing steps become rests.
    pub steps: Vec<NoteStep>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct NoteSetParams {
    /// Note instrument id; defaults to the first `tb303`.
    #[serde(default)]
    pub instrument: Option<String>,
    /// 0-based step index.
    pub step: u32,
    pub note: NoteStep,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct NotesResult {
    pub instrument: String,
    /// Active length (`sequencer.length`).
    pub length: u32,
    /// All `MAX_STEPS` steps.
    pub steps: Vec<NoteStep>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct PatternSetParams {
    /// Drum instrument id; defaults to the first `tr808`.
    #[serde(default)]
    pub instrument: Option<String>,
    pub voice: Voice,
    /// Step levels from step 0; missing trailing steps are cleared.
    pub steps: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct SetStepParams {
    /// Drum instrument id; defaults to the first `tr808`.
    #[serde(default)]
    pub instrument: Option<String>,
    pub voice: Voice,
    /// 0-based step index.
    pub step: u32,
    /// 0 = off, 1 = on, 2 = accent.
    pub level: u8,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ToggleStepParams {
    /// Drum instrument id; defaults to the first `tr808`.
    #[serde(default)]
    pub instrument: Option<String>,
    pub voice: Voice,
    pub step: u32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct StepResult {
    pub instrument: String,
    pub voice: Voice,
    pub step: u32,
    pub level: u8,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct PatternClearParams {
    /// Drum instrument id; defaults to the first `tr808`.
    #[serde(default)]
    pub instrument: Option<String>,
    /// Clear only this voice; all voices if omitted.
    #[serde(default)]
    pub voice: Option<Voice>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct TriggerParams {
    /// Defaults to the first `tr808` when `voice` is given, else the first
    /// `tb303`.
    #[serde(default)]
    pub instrument: Option<String>,
    /// Drum voice to play (drum instruments).
    #[serde(default)]
    pub voice: Option<Voice>,
    /// MIDI note to play for half a step (note instruments).
    #[serde(default)]
    pub note: Option<u8>,
    /// 0..1, defaults to 1.
    #[serde(default)]
    pub velocity: Option<f32>,
}

// ---- controller ----------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct PadParams {
    /// 0-based row (track).
    pub row: u32,
    /// 0-based column within the current page.
    pub col: u32,
    /// true = press, false = release. Omit for a full tap.
    #[serde(default)]
    pub pressed: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct KnobParams {
    /// 0-based knob index.
    pub index: u32,
    /// Normalized position 0..1 (as from a 0..127 MIDI CC).
    pub value: f64,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ControllerModeParams {
    /// Drum instrument the controller drives.
    #[serde(default)]
    pub target: Option<String>,
    #[serde(default)]
    pub knob_mode: Option<KnobMode>,
    #[serde(default)]
    pub page: Option<u32>,
    #[serde(default)]
    pub follow: Option<bool>,
}

// ---- midi ----------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct MidiPortsResult {
    pub inputs: Vec<String>,
    pub outputs: Vec<String>,
    pub connections: Vec<MidiConnection>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct MidiConnectParams {
    /// Input port name (exact or case-insensitive substring).
    pub input: String,
    /// Output port for feedback (LEDs). Defaults to the output matching the input.
    #[serde(default)]
    pub output: Option<String>,
    pub kind: DeviceKind,
    /// For `keyboard`: the instrument to play (default: the first `tb303`).
    #[serde(default)]
    pub instrument: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct MidiDisconnectParams {
    pub input: String,
}

// ---- project -------------------------------------------------------------

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ProjectSaveParams {
    /// Engine-side bundle path (e.g. `songs/beat.4s`). Relative paths resolve
    /// under the daemon's data dir. Defaults to the current project path.
    #[serde(default)]
    pub path: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ProjectLoadParams {
    pub path: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct ProjectListResult {
    /// Project bundles found in the daemon's projects dir (engine-side paths).
    pub projects: Vec<String>,
}

// ---- render --------------------------------------------------------------

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct RenderParams {
    /// Number of 4/4 bars to render (default 1).
    #[serde(default)]
    pub bars: Option<f64>,
    /// Extra seconds after the last bar so tails ring out (default 0).
    #[serde(default)]
    pub tail: Option<f64>,
    /// Engine-side WAV path. Relative paths resolve under the data dir.
    #[serde(default)]
    pub path: Option<String>,
    #[serde(default)]
    pub sample_rate: Option<u32>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct RenderResult {
    pub path: String,
    pub sample_rate: u32,
    pub duration: f64,
    /// Peak absolute sample value across channels.
    pub peak: f32,
    pub rms: f32,
    pub left: Level,
    pub right: Level,
    /// Onset times (seconds) detected from the audio itself.
    pub onsets: Vec<f64>,
    /// What the sequencer actually fired, for comparison with `onsets`.
    pub triggers: Vec<RenderTrigger>,
}

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
pub struct Level {
    pub peak: f32,
    pub rms: f32,
}

// ---------------------------------------------------------------------------

api! {
    /// Identify this client and check protocol compatibility.
    Hello = "session.hello" (HelloParams) -> HelloResult;
    /// Full state snapshot.
    StateGet = "state.get" (Empty) -> Snapshot;
    /// Start receiving `event` notifications on this connection.
    EventsSubscribe = "events.subscribe" (SubscribeParams) -> SubscribeResult;
    /// Stop receiving events.
    EventsUnsubscribe = "events.unsubscribe" (Empty) -> Empty;

    /// List parameters, optionally filtered by path prefix.
    ParamList = "param.list" (ParamListParams) -> ParamListResult;
    /// Read one parameter.
    ParamGet = "param.get" (ParamGetParams) -> ParamValue;
    /// Set one parameter (clamped to its range).
    ParamSet = "param.set" (ParamSetParams) -> ParamValue;

    /// Start the sequencer from step 1.
    TransportPlay = "transport.play" (Empty) -> TransportState;
    /// Stop the sequencer.
    TransportStop = "transport.stop" (Empty) -> TransportState;

    /// Available instrument types, with their outputs and parameters.
    InstrumentTypes = "instrument.types" (Empty) -> InstrumentTypesResult;
    /// Instruments in creation order.
    InstrumentList = "instrument.list" (Empty) -> InstrumentListResult;
    /// Add an instrument; by default on a new channel.
    InstrumentAdd = "instrument.add" (InstrumentAddParams) -> InstrumentInfo;
    /// Remove an instrument (and channels left empty, unless kept).
    InstrumentRemove = "instrument.remove" (InstrumentRemoveParams) -> Graph;
    /// Add a mixer channel (lowest free number).
    ChannelAdd = "channel.add" (ChannelAddParams) -> ChannelInfo;
    /// Remove a mixer channel; sources routed to it are unrouted.
    ChannelRemove = "channel.remove" (ChannelRemoveParams) -> Graph;
    /// Rename a mixer channel.
    ChannelRename = "channel.rename" (ChannelRenameParams) -> ChannelInfo;
    /// Route an instrument output to a channel, or unroute it.
    RouteSet = "route.set" (RouteSetParams) -> Graph;

    /// Read a drum pattern (one voice or all).
    PatternGet = "pattern.get" (PatternGetParams) -> PatternResult;
    /// Replace one voice's steps.
    PatternSet = "pattern.set" (PatternSetParams) -> TrackPattern;
    /// Set one step's level.
    PatternSetStep = "pattern.set_step" (SetStepParams) -> StepResult;
    /// Toggle one step between off and on.
    PatternToggleStep = "pattern.toggle_step" (ToggleStepParams) -> StepResult;
    /// Clear one voice or the whole pattern.
    PatternClear = "pattern.clear" (PatternClearParams) -> PatternResult;
    /// Read a note pattern.
    PatternGetNotes = "pattern.get_notes" (NotesGetParams) -> NotesResult;
    /// Replace a note pattern.
    PatternSetNotes = "pattern.set_notes" (NotesSetParams) -> NotesResult;
    /// Set one step of a note pattern.
    PatternSetNote = "pattern.set_note" (NoteSetParams) -> NotesResult;

    /// Play a drum voice or a note immediately (audition).
    VoiceTrigger = "voice.trigger" (TriggerParams) -> Empty;

    /// Controller state (mode, page, LEDs, device).
    ControllerGet = "controller.get" (Empty) -> ControllerState;
    /// Press/release a grid pad, as if on the Livid Block.
    ControllerPress = "controller.press" (PadParams) -> ControllerState;
    /// Turn a knob, as if on the Livid Block.
    ControllerKnob = "controller.knob" (KnobParams) -> ControllerState;
    /// Change target instrument, knob mode, page, or follow.
    ControllerSetMode = "controller.set_mode" (ControllerModeParams) -> ControllerState;

    /// List MIDI ports and active connections.
    MidiPorts = "midi.ports" (Empty) -> MidiPortsResult;
    /// Connect a MIDI input (and optional output) as a device.
    MidiConnect = "midi.connect" (MidiConnectParams) -> MidiPortsResult;
    /// Disconnect a MIDI input.
    MidiDisconnect = "midi.disconnect" (MidiDisconnectParams) -> MidiPortsResult;

    /// Reset to a fresh default project.
    ProjectNew = "project.new" (Empty) -> ProjectInfo;
    /// Save the project bundle.
    ProjectSave = "project.save" (ProjectSaveParams) -> ProjectInfo;
    /// Load a project bundle.
    ProjectLoad = "project.load" (ProjectLoadParams) -> ProjectInfo;
    /// List project bundles in the daemon's projects dir.
    ProjectList = "project.list" (Empty) -> ProjectListResult;

    /// Render the current project offline to a WAV and analyze it.
    RenderOffline = "render.offline" (RenderParams) -> RenderResult;
    /// Audio device status.
    EngineStatus = "engine.status" (Empty) -> AudioStatus;

    /// Daemon identity: pid, version, URL, data dir, uptime.
    DaemonInfo = "daemon.info" (Empty) -> DaemonInfo;
    /// Shut the daemon down gracefully (responds first, then exits).
    DaemonShutdown = "daemon.shutdown" (Empty) -> Empty;
}

/// Build a `Request` from a method name and JSON params (missing/null params
/// are treated as `{}`).
pub fn parse_request(method: &str, params: Option<serde_json::Value>) -> Result<Request, String> {
    let params = match params {
        None | Some(serde_json::Value::Null) => serde_json::json!({}),
        Some(p) => p,
    };
    if !METHODS.contains(&method) {
        return Err(format!("unknown method '{method}'"));
    }
    serde_json::from_value(serde_json::json!({ "method": method, "params": params }))
        .map_err(|e| format!("invalid params for '{method}': {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn request_wire_format() {
        let r = Request::ParamSet(ParamSetParams { path: "mixer.1.volume".into(), value: 0.35 });
        let j = serde_json::to_value(&r).unwrap();
        assert_eq!(j["method"], "param.set");
        assert_eq!(j["params"]["value"], 0.35);
        assert_eq!(r.method(), "param.set");
    }

    #[test]
    fn parse_with_missing_params() {
        assert!(matches!(parse_request("state.get", None).unwrap(), Request::StateGet(_)));
        assert!(matches!(
            parse_request("pattern.clear", Some(serde_json::Value::Null)).unwrap(),
            Request::PatternClear(PatternClearParams { instrument: None, voice: None })
        ));
        assert!(parse_request("nope", None).is_err());
        assert!(parse_request("param.set", Some(serde_json::json!({"path": 1}))).is_err());
    }
}
